server:
  port: 8085

spring:
  application:
    name: dyc-calculation
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/


ribbon:
  ReadTimeout: 6000   # 请求处理的超时时间
  ConnectTimeout: 6000 # 请求连接的超时时间
  eureka:
      enabled: true

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000    # 连接超时时间
        readTimeout: 5000       # 读数据超时时间
